### ISSUE TITLE
eWallet_MobileApp(Profile Update) #107

### ISSUE THREAD

**Issue by farahmohamad** [TNGSB/eWallet#128] opened 2016-11-16 01:47 UTC
[Defect_Mobile App #107.xlsx](https://github.com/TNGSB/eWallet/files/593569/Defect_Mobile.App.107.xlsx)

Test Description : To verify the fields input for "Phone" update - alphanumeric characters
Defect Description : System allowed alphanumeric characters input for Android and IOS 
Tested in Build : 31 Android and 34 IOS

Refer attachment for POT

**Comment by BavaniS** [comment] 2016-11-16 08:40
duplicate of #129

**Closed as completed by BavaniS** 2016-11-16 08:40 UTC
Labels: Defect - Medium (Sev-3)
